project:
  type: website

website:
  title: "EPPS 6323 Knowledge Mining"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Assignment_1.qmd
        text: Assignment 1
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true
